namespace AiService.Services
{
    /// <summary>
    /// Used for automated tests and docker-compose.test without calling OpenAI.
    /// Enable with environment variable USE_FAKE_AI=true.
    /// </summary>
    public class FakeLessonGenerator : ILessonGenerator
    {
        public Task<string> GenerateLesson(string category, string subCategory, string userPrompt) =>
            Task.FromResult(
                $"# {subCategory}\n\nTest lesson for **{category}**.\n\nRequest: {userPrompt}\n\n## Summary\nGenerated by test AI service.");
    }
}
