using LearningPlatformApi.Services;

namespace LearningPlatformApi.Tests.Fakes
{
    public class FakeAiService : IAiService
    {
        public Task<string> GenerateLesson(string category, string subCategory, string userPrompt) =>
            Task.FromResult(
                $"# {subCategory}\n\nTest lesson for **{category}**.\n\nRequest: {userPrompt}\n\n## Summary\nGenerated by test AI service.");
    }
}
